import { Product, Review, Order, Address } from './types';

export const products: Product[] = [
  {
    id: '1',
    name: 'Adaptogen Complex',
    description: 'Premium adaptogenic blend with ashwagandha, rhodiola, and holy basil to support stress response and mental clarity.',
    price: 49.99,
    compareAtPrice: 64.99,
    category: 'Supplements',
    rating: 4.8,
    reviewCount: 243,
    images: [
      'https://images.unsplash.com/photo-1714411892980-d1fa234f61ec?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx3ZWxsbmVzcyUyMHN1cHBsZW1lbnRzJTIwYm90dGxlfGVufDF8fHx8MTc2MDkyNzQ0OHww&ixlib=rb-4.1.0&q=80&w=1080',
    ],
    stock: 45,
    tags: ['New', 'Bestseller'],
    sku: 'VERVE-ADT-001',
  },
  {
    id: '2',
    name: 'Radiance Face Serum',
    description: 'Vitamin C and hyaluronic acid serum for luminous, hydrated skin. Vegan and cruelty-free.',
    price: 68.00,
    compareAtPrice: 85.00,
    category: 'Skincare',
    rating: 4.9,
    reviewCount: 512,
    images: [
      'https://images.unsplash.com/photo-1605204376600-72ed73f1f9ec?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxmYWNlJTIwc2VydW0lMjBza2luY2FyZXxlbnwxfHx8fDE3NjA5Mjc0NTF8MA&ixlib=rb-4.1.0&q=80&w=1080',
    ],
    colors: [
      { name: 'Original', hex: '#F5E6D3' },
    ],
    stock: 67,
    tags: ['Bestseller', 'Eco'],
    sku: 'VERVE-SER-002',
  },
  {
    id: '3',
    name: 'Premium Yoga Mat',
    description: 'Eco-friendly cork and natural rubber yoga mat with superior grip and cushioning. 5mm thickness.',
    price: 89.99,
    category: 'Fitness',
    rating: 4.7,
    reviewCount: 189,
    images: [
      'https://images.unsplash.com/photo-1746796751590-a8c0f15d4900?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx5b2dhJTIwbWF0JTIwZml0bmVzc3xlbnwxfHx8fDE3NjA4Mjc5Nzl8MA&ixlib=rb-4.1.0&q=80&w=1080',
    ],
    colors: [
      { name: 'Forest', hex: '#2D5016' },
      { name: 'Ocean', hex: '#1E3A8A' },
      { name: 'Sunset', hex: '#DC2626' },
    ],
    stock: 23,
    tags: ['Eco'],
    sku: 'VERVE-YOG-003',
  },
  {
    id: '4',
    name: 'Essential Oil Diffuser Set',
    description: 'Ultrasonic aromatherapy diffuser with 6 pure essential oils: lavender, eucalyptus, peppermint, tea tree, lemon, and sweet orange.',
    price: 79.99,
    compareAtPrice: 99.99,
    category: 'Aromatherapy',
    rating: 4.6,
    reviewCount: 321,
    images: [
      'https://images.unsplash.com/photo-1537035448858-6d703dbc320f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxlc3NlbnRpYWwlMjBvaWwlMjBhcm9tYXRoZXJhcHl8ZW58MXx8fHwxNzYwOTI3NDQ5fDA&ixlib=rb-4.1.0&q=80&w=1080',
    ],
    stock: 34,
    tags: ['Sale'],
    sku: 'VERVE-ARO-004',
  },
  {
    id: '5',
    name: 'Organic Herbal Tea Collection',
    description: 'Curated selection of 12 organic herbal teas for relaxation, energy, and wellness. 120 biodegradable tea bags.',
    price: 34.99,
    category: 'Wellness',
    rating: 4.8,
    reviewCount: 456,
    images: [
      'https://images.unsplash.com/photo-1594137052297-e55c3c6b33f9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxoZXJiYWwlMjB0ZWElMjB3ZWxsbmVzc3xlbnwxfHx8fDE3NjA5MTQzODl8MA&ixlib=rb-4.1.0&q=80&w=1080',
    ],
    stock: 89,
    tags: ['Eco', 'Bestseller'],
    sku: 'VERVE-TEA-005',
  },
  {
    id: '6',
    name: 'Meditation Cushion',
    description: 'Organic cotton zafu meditation cushion filled with buckwheat hulls. Supportive and eco-friendly.',
    price: 54.99,
    category: 'Wellness',
    rating: 4.7,
    reviewCount: 134,
    images: [
      'https://images.unsplash.com/photo-1597307509190-e33cb9fb3ff7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtZWRpdGF0aW9uJTIwY3VzaGlvbnxlbnwxfHx8fDE3NjA5Mjc0NTB8MA&ixlib=rb-4.1.0&q=80&w=1080',
    ],
    colors: [
      { name: 'Natural', hex: '#E5D4B5' },
      { name: 'Charcoal', hex: '#2D3748' },
      { name: 'Sage', hex: '#7C9885' },
    ],
    stock: 12,
    tags: ['New'],
    sku: 'VERVE-MED-006',
  },
  {
    id: '7',
    name: 'Plant-Based Protein Powder',
    description: 'Organic pea and brown rice protein blend with natural vanilla flavor. 20g protein per serving.',
    price: 44.99,
    compareAtPrice: 54.99,
    category: 'Supplements',
    rating: 4.5,
    reviewCount: 678,
    images: [
      'https://images.unsplash.com/photo-1579722822515-1562ad83b940?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwcm90ZWluJTIwcG93ZGVyJTIwZml0bmVzc3xlbnwxfHx8fDE3NjA5Mjc0NTB8MA&ixlib=rb-4.1.0&q=80&w=1080',
    ],
    stock: 156,
    tags: ['Bestseller'],
    sku: 'VERVE-PRO-007',
  },
  {
    id: '8',
    name: 'Natural Body Cream',
    description: 'Deeply nourishing body cream with shea butter, coconut oil, and vitamin E. For all skin types.',
    price: 38.00,
    category: 'Skincare',
    rating: 4.8,
    reviewCount: 289,
    images: [
      'https://images.unsplash.com/photo-1661347243240-5ce7c9992369?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxuYXR1cmFsJTIwc2tpbmNhcmUlMjBjcmVhbXxlbnwxfHx8fDE3NjA5MDU4Nzl8MA&ixlib=rb-4.1.0&q=80&w=1080',
    ],
    stock: 0,
    tags: [],
    sku: 'VERVE-SKN-008',
  },
  {
    id: '9',
    name: 'Resistance Bands Set',
    description: 'Professional resistance bands in 5 resistance levels with handles, door anchor, and carrying bag.',
    price: 39.99,
    category: 'Fitness',
    rating: 4.6,
    reviewCount: 234,
    images: [
      'https://images.unsplash.com/photo-1584827386916-b5351d3ba34b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxyZXNpc3RhbmNlJTIwYmFuZHMlMjB3b3Jrb3V0fGVufDF8fHx8MTc2MDg5NDU5NXww&ixlib=rb-4.1.0&q=80&w=1080',
    ],
    colors: [
      { name: 'Rainbow', hex: '#EF4444' },
    ],
    stock: 78,
    tags: [],
    sku: 'VERVE-FIT-009',
  },
  {
    id: '10',
    name: 'Wellness Journal',
    description: 'Guided daily journal for mindfulness, gratitude, and goal-setting. 180 days of prompted entries.',
    price: 29.99,
    category: 'Wellness',
    rating: 4.9,
    reviewCount: 567,
    images: [
      'https://images.unsplash.com/photo-1594997652537-2e2dce4ebf28?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx3ZWxsbmVzcyUyMGpvdXJuYWwlMjBub3RlYm9va3xlbnwxfHx8fDE3NjA5Mjc0NTF8MA&ixlib=rb-4.1.0&q=80&w=1080',
    ],
    colors: [
      { name: 'Midnight', hex: '#1E293B' },
      { name: 'Blush', hex: '#FCA5A5' },
      { name: 'Sage', hex: '#86EFAC' },
    ],
    stock: 145,
    tags: ['New', 'Bestseller'],
    sku: 'VERVE-JOU-010',
  },
  {
    id: '11',
    name: 'Insulated Water Bottle',
    description: 'Stainless steel vacuum-insulated bottle keeps drinks cold for 24h or hot for 12h. BPA-free. 32oz capacity.',
    price: 34.99,
    category: 'Fitness',
    rating: 4.7,
    reviewCount: 892,
    images: [
      'https://images.unsplash.com/photo-1601507793214-77d2a926582a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx3YXRlciUyMGJvdHRsZSUyMGh5ZHJhdGlvbnxlbnwxfHx8fDE3NjA5Mjc0NTJ8MA&ixlib=rb-4.1.0&q=80&w=1080',
    ],
    colors: [
      { name: 'Mint', hex: '#6EE7B7' },
      { name: 'Slate', hex: '#475569' },
      { name: 'Coral', hex: '#FB923C' },
      { name: 'Lavender', hex: '#C4B5FD' },
    ],
    stock: 234,
    tags: ['Eco'],
    sku: 'VERVE-HYD-011',
  },
  {
    id: '12',
    name: 'Organic Body Lotion',
    description: 'Certified organic body lotion with aloe vera, jojoba oil, and calendula. Lightweight and fast-absorbing.',
    price: 42.00,
    category: 'Skincare',
    rating: 4.8,
    reviewCount: 412,
    images: [
      'https://images.unsplash.com/photo-1668025790616-750caa376cd6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxvcmdhbmljJTIwYm9keSUyMGxvdGlvbnxlbnwxfHx8fDE3NjA5Mjc0NTR8MA&ixlib=rb-4.1.0&q=80&w=1080',
    ],
    stock: 8,
    tags: ['Eco'],
    sku: 'VERVE-LOT-012',
  },
];

export const reviews: Review[] = [
  {
    id: 'r1',
    productId: '1',
    author: 'Sarah M.',
    rating: 5,
    date: '2025-10-15',
    verified: true,
    comment: 'This adaptogen blend has completely transformed my stress levels. I feel calmer and more focused throughout the day.',
  },
  {
    id: 'r2',
    productId: '1',
    author: 'James K.',
    rating: 4,
    date: '2025-10-10',
    verified: true,
    comment: 'Good product, noticed improvements after 2 weeks. Wish it came in a larger size.',
  },
  {
    id: 'r3',
    productId: '2',
    author: 'Emily R.',
    rating: 5,
    date: '2025-10-12',
    verified: true,
    comment: 'My skin has never looked better! The serum absorbs quickly and leaves my face glowing.',
  },
  {
    id: 'r4',
    productId: '10',
    author: 'Michael T.',
    rating: 5,
    date: '2025-10-08',
    verified: true,
    comment: 'The prompts in this journal are thoughtful and help me stay consistent with my practice.',
  },
];

export const sampleOrders: Order[] = [
  {
    id: 'ORD-2025-001',
    date: '2025-10-15',
    status: 'delivered',
    total: 158.97,
    items: [
      { product: products[0], quantity: 1 },
      { product: products[4], quantity: 2 },
      { product: products[9], quantity: 1 },
    ],
  },
  {
    id: 'ORD-2025-002',
    date: '2025-10-18',
    status: 'shipped',
    total: 68.00,
    items: [
      { product: products[1], quantity: 1 },
    ],
  },
  {
    id: 'ORD-2025-003',
    date: '2025-10-19',
    status: 'paid',
    total: 124.98,
    items: [
      { product: products[2], quantity: 1 },
      { product: products[10], quantity: 1 },
    ],
  },
];

export const sampleAddresses: Address[] = [
  {
    id: 'addr1',
    name: 'Home',
    street: '742 Evergreen Terrace',
    city: 'Springfield',
    state: 'IL',
    zip: '62701',
    country: 'United States',
    phone: '(555) 123-4567',
    isDefault: true,
  },
  {
    id: 'addr2',
    name: 'Work',
    street: '123 Business Blvd, Suite 400',
    city: 'Chicago',
    state: 'IL',
    zip: '60601',
    country: 'United States',
    phone: '(555) 987-6543',
    isDefault: false,
  },
];

export const categories = [
  { name: 'All Products', slug: 'all', count: 12 },
  { name: 'Supplements', slug: 'supplements', count: 2 },
  { name: 'Skincare', slug: 'skincare', count: 3 },
  { name: 'Fitness', slug: 'fitness', count: 3 },
  { name: 'Aromatherapy', slug: 'aromatherapy', count: 1 },
  { name: 'Wellness', slug: 'wellness', count: 3 },
];
